server:
  port: 8080

spring:
  application:
    name: campus-ordering-server
  profiles:
    active: dev
  main:
    allow-circular-references: true
  data:
    redis:
      host: ${campus.ordering.redis.host}
      port: ${campus.ordering.redis.port}


  datasource:
    druid:
      driver-class-name: ${campus.ordering.datasource.driver-class-name}
      url: jdbc:mysql://${campus.ordering.datasource.host}:${campus.ordering.datasource.port}/${campus.ordering.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${campus.ordering.datasource.username}
      password: ${campus.ordering.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.damien.campusordering.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      damien:
        campusordering:
          mapper: debug
          service: info
          controller: info

campus:
  ordering:
    jwt:
      admin-secret-key: dGhpcyBpcyBhbiBleGFtcGxlIGtleSBmb3IgTmFjb3MgdG9rZW4=
      admin-ttl: 7200000
      admin-token-name: token

    alioss :
      endpoint: ${campus.ordering.alioss.endpoint}
      access-key-id: ${campus.ordering.alioss.accessKeyId}
      access-key-secret: ${campus.ordering.alioss.accessKeySecret}
      bucket-name: ${campus.ordering.alioss.bucketName}
