campus:
  ordering:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: 127.0.0.1
      port: 13306
      database: campus_ordering
      username: root
      password: 123456
    alioss:
      endpoint:
      access-key-id:
      access-key-secret:
      bucket-name:
    wechat:
      appid: wxa2875adad18a4383
      secret: cc35085adb977c629ee5222bd8b1f343
      mchid:
      mchSerialNo:
      privateKeyFilePath:
      apiV3Key:
      weChatPayCertFilePath:
      notifyUrl:

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 16379

